version: '3.7'

services:
  hggd:
    image: hggd/test
    restart: unless-stopped
    container_name: hggd
    ports:
      - 5000:5000
    volumes:
      - ./data:/mydir/data/
      - ./user_templates:/mydir/src/templates/user_templates/

volumes:
  data:
  user_templates:

networks:
  default:
    external:
      name: hggd_network
