version: '3.8'

services:
  hggd:
    image: hggd/test
    restart: unless-stopped
    container_name: hggd
    ports:
      - 5000:5000
    volumes:
      - hggd-data:/data

volumes:
   hggd-data:

networks:
  default:
    external:
      name: ohtup
