version: '3.7'

services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
     -  WATCHTOWER_CLEANUP=true
     -  WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
